sudo: required
services:
  - docker

before_install:
  - docker build -t vifarinde/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vifarinde/multi-docker npm test

after_success:
  - docker build -t vifarinde/multi-client ./client
  - docker build -t vifarinde/multi-server ./server
  - docker build -t vifarinde/multi-nginx ./nginx
  - docker build -t vifarinde/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vifarinde/multi-client
  - docker push vifarinde/multi-nginx
  - docker push vifarinde/multi-worker
  - docker push vifarinde/multi-server

language: generic

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "multiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-361073341746"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS"
